default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: postgres
  port: 5432
  password: 1234
  pool: 5

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: postgres